### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by wangbokun** [netxfly/sec_check#2]
Hi,

这一步报错，看到你说不是必须的，就跳过了，
➜  go-yara git:(master) go get github.com/hillu/go-yara
# github.com/hillu/go-yara
./config_yara38.go:12:39: could not determine kind of name for C.YR_CONFIG_MAX_MATCH_DATA

然后build报这个错，有没有遇到过？ mac os
➜  go-yara git:(master) go build --tags yara_static --tags no_pkg_config --tags yara3.7 main.go
# command-line-arguments
Undefined symbols for architecture x86_64:
  "_yr_finalize", referenced from:
      __cgo_a129ae427a70_Cfunc_yr_finalize in _x002.o
     (maybe you meant: __cgo_a129ae427a70_Cfunc_yr_finalize)
  "_yr_initialize", referenced from:
      __cgo_a129ae427a70_Cfunc_yr_initialize in _x002.o
     (maybe you meant: __cgo_a129ae427a70_Cfunc_yr_initialize)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by wangbokun** [comment]
看着还是yara得问题
go build  --tags no_pkg_config   main.go
# github.com/hillu/go-yara
../../github.com/hillu/go-yara/config_yara38.go:12:39: could not determine kind of name for C.YR_CONFIG_MAX_MATCH_DATA



const ConfigMaxMatchData ConfigName = C.YR_CONFIG_MAX_MATCH_DATA
![Uploading image.png…]()

**Comment by netxfly** [comment]
建议用centos与ubuntu编译，这个检测脚本还没支持MAC OS
